name: My First Pipeline

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Pipeline is running!"

     - name: Set up Python
       uses: actions/setup-python@v5
       with:
          python-version: '3.x'

    - name: Run server check script
      run: python3 readjson.py
